from time import strftime, localtime

class Config():
    '''
    Configuration for ARMer
    '''
    # -----------------------------
    # debug output level
    #
    debug = 0
    # -----------------------------
    # watermark for script generation
    # 
    WATERMARK = f'Script generated by EnzyHTP in {strftime("%Y-%m-%d %H:%M:%S", localtime())}'
    # -----------------------------
    # place to hold all submitted job id in current run
    # 
    JOB_ID_LOG_PATH = '' # default (job_obj.sub_dir/submitted_job_ids.log)
